volumes:
  pg_data:
  static:
  media:

services:
  frontend:
    hostname: frontend
    container_name: frontend
    image: kirillpudov/kittygram_frontend
    volumes:
      - static:/app/build
  
  backend:
    hostname: backend
    container_name: backend
    image: kirillpudov/kittygram_backend
    env_file: ".env"
    networks:
      - kitty
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - postgres
      - frontend
  
  gateway:
    hostname: gateway
    container_name: gateway
    image: kirillpudov/kittygram_gateway
    networks:
      - kitty
    depends_on:
      - frontend
      - backend
      - postgres
    volumes:
      - static:/static
      - media:/media
    ports:
      - 80:80
  
  postgres:
    image: postgres:13.10
    hostname: postgres
    container_name: postgres
    env_file: .env
    networks:
      - kitty
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  kitty:
    driver: bridge