version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  frontend:
    hostname: frontend
    container_name: frontend
    image: kirillpudov/kittygram_frontend
    volumes:
      - static:/app/build
  
  backend:
    hostname: backend
    container_name: backend
    image: kirillpudov/kittygram_backend
    env_file: ".env"
    volumes:
      - static:/app/frontend
      - media:/app/media
    depends_on:
      - postgres
      - frontend
  
  gateway:
    hostname: gateway
    container_name: gateway
    image: kirillpudov/kittygram_gateway
    volumes:
      - static:/static
    ports:
      - 80:80
  
  postgres:
    image: postgres:13.10
    hostname: postgres
    container_name: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data