name: Terraform

on:
  workflow_call:
    outputs:
      ip_addr:
        description: "IP addr of kitty-vm"
        value: ${{ jobs.terraform.outputs.ip }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      ip: ${{ steps.apply.outputs.ip }}
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.11.2
      - name: Terraform init
        working-directory: ./infra
        run: |
          echo "provider_installation {network_mirror {url = "https://terraform-mirror.yandexcloud.net/"include = ["registry.terraform.io/*/*"]}direct {exclude = ["registry.terraform.io/*/*"]}}" > ~/.terraformrc
          terraform init --upgrade
      - name: Terraform Plan
        working-directory: ./infra
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan
        env:
          TF_VAR_yandex_token: ${{ secrets.YANDEX_TOKEN }}
          TF_VAR_yandex_cloud_id: ${{ secrets.YANDEX_CLOUD_ID }}
          TF_VAR_yandex_folder_id: ${{ secrets.YANDEX_FOLDER_ID }}
          TF_VAR_yandex_zone: ${{ secrets.YANDEX_ZONE }}
          TF_VAR_ssh_key: ${{ secrets.SSH_KEY }}
      - name: Terraform apply
        id: apply
        working-directory: ./infra
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform apply
          echo "ip_addr=`terraform output -raw instalce_ip_addr`"
        env:
          TF_VAR_yandex_token: ${{ secrets.YANDEX_TOKEN }}
          TF_VAR_yandex_cloud_id: ${{ secrets.YANDEX_CLOUD_ID }}
          TF_VAR_yandex_folder_id: ${{ secrets.YANDEX_FOLDER_ID }}
          TF_VAR_yandex_zone: ${{ secrets.YANDEX_ZONE }}
          TF_VAR_ssh_key: ${{ secrets.SSH_KEY }}
      - name: Terraform destroy
        working-directory: ./infra
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy
        env:
          TF_VAR_yandex_token: ${{ secrets.YANDEX_TOKEN }}
          TF_VAR_yandex_cloud_id: ${{ secrets.YANDEX_CLOUD_ID }}
          TF_VAR_yandex_folder_id: ${{ secrets.YANDEX_FOLDER_ID }}
          TF_VAR_yandex_zone: ${{ secrets.YANDEX_ZONE }}
          TF_VAR_ssh_key: ${{ secrets.SSH_KEY }}